version: 2

jobs:
  like:
    docker:
      - image: circleci/node:10.11.0

    steps:
      - checkout
      - restore_cache:
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: yarn install

      - save_cache:
          paths: node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: yarn start

workflows:
  version: 2

  daily:
    triggers:
      - schedule:
          cron: 10 10 * * *
    jobs:
      - like

  on_push:
    jobs:
      - like

