version: 2

jobs:
  build:
    docker:
      - image: circleci/node:10.11.0-browsers

    steps:
      - checkout
      - restore_cache:
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: yarn install

      - save_cache:
          paths: node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: yarn start

workflows:

  version: 2

  # daily:
  #   triggers:
  #     - schedule:
  #         cron: 5 9,12,15,18,21 * * *
  #         filters:
  #           branches:
  #             only:
  #               - master
  #   jobs:
  #     - build

  on_push:
    jobs:
      - build

